services:
  - type: web
    name: importadora-market-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://TU-BACKEND.onrender.com/api/v1

