"""add_secondary_and_alternative_images

Revision ID: 05769c5ff244
Revises: c40f5f8e47d6
Create Date: 2026-05-31 20:47:35.864028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05769c5ff244'
down_revision: Union[str, Sequence[str], None] = 'c40f5f8e47d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_secundaria_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('imagen_alternativa_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('imagen_alternativa_url')
        batch_op.drop_column('imagen_secundaria_url')

    # ### end Alembic commands ###
