"""add_role_field_to_users

Revision ID: 41e832877322
Revises: 1c0c4b464649
Create Date: 2026-05-22 13:37:36.855949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e832877322'
down_revision: Union[str, Sequence[str], None] = '1c0c4b464649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='cliente'))
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True, server_default=sa.text('0')))
        batch_op.drop_column('role')
    # ### end Alembic commands ###

